name: MyOrderAppSwift
targets:
  MyOrderAppSwift:
    type: framework
    platform: iOS
    deploymentTarget: "9.0"
    sources: [MyOrderAppSwift]
    info:
      path: ./Info.plist
      version: 1.0.1
    settings:
      APPLICATION_EXTENSION_API_ONLY: true
    scheme: {}
    
