//
// Catalog.swift
//
// Generated by openapi-generator
// https://openapi-generator.tech
//

import Foundation

@objc public class MOACatalog: NSObject, Codable {

    public var categories: [Category]?
    public var merchant: Merchant?
    public var _id: String?
    public var createDate: Date?
    public var updateDate: Date?

    public init(categories: [Category]? = nil, merchant: Merchant? = nil, _id: String? = nil, createDate: Date? = nil, updateDate: Date? = nil) {
        self.categories = categories
        self.merchant = merchant
        self._id = _id
        self.createDate = createDate
        self.updateDate = updateDate
    }

    public enum CodingKeys: String, CodingKey, CaseIterable {
        case categories
        case merchant
        case _id = "id"
        case createDate
        case updateDate
    }

}
