//
// Category.swift
//
// Generated by openapi-generator
// https://openapi-generator.tech
//

import Foundation

public class Category: Codable, Hashable {

    public var catalog: Catalog?
    public var items: [Item]?
    public var id: String?
    public var createDate: Date?
    public var updateDate: Date?
    public var squareId: String?
    public var name: String?

    public init(catalog: Catalog? = nil, items: [Item]? = nil, id: String? = nil, createDate: Date? = nil, updateDate: Date? = nil, squareId: String? = nil, name: String? = nil) {
        self.catalog = catalog
        self.items = items
        self.id = id
        self.createDate = createDate
        self.updateDate = updateDate
        self.squareId = squareId
        self.name = name
    }

}
