//
// CustomerUpdateInput.swift
//
// Generated by openapi-generator
// https://openapi-generator.tech
//

import Foundation

@objc public class CustomerUpdateInput: NSObject, Codable {

    public var _id: String?

    public init(_id: String? = nil) {
        self._id = _id
    }

    public enum CodingKeys: String, CodingKey, CaseIterable {
        case _id = "id"
    }

}
