//
// CustomerCreateInput.swift
//
// Generated by openapi-generator
// https://openapi-generator.tech
//

import Foundation

public class CustomerCreateInput: Codable, Hashable {

    public var email: String
    public var password: String
    public var merchantId: String

    public init(email: String, password: String, merchantId: String) {
        self.email = email
        self.password = password
        self.merchantId = merchantId
    }

}
