//
// CustomerUpdateInput.swift
//
// Generated by openapi-generator
// https://openapi-generator.tech
//

import Foundation

public class CustomerUpdateInput: Codable, Hashable {

    public var id: String?

    public init(id: String? = nil) {
        self.id = id
    }

}
