//
// CustomerUpdateInput.swift
//
// Generated by openapi-generator
// https://openapi-generator.tech
//

import Foundation

public struct CustomerUpdateInput: Codable {

    public var id: String?

    public init(id: String? = nil) {
        self.id = id
    }

}
