//
// InlineResponse200.swift
//
// Generated by openapi-generator
// https://openapi-generator.tech
//

import Foundation

@objc public class InlineResponse200: NSObject, Codable {

    public var status: String?
    public var info: [String: [String: String]]?
    public var error: [String: [String: String]]?
    public var details: [String: [String: String]]?

    public init(status: String? = nil, info: [String: [String: String]]? = nil, error: [String: [String: String]]? = nil, details: [String: [String: String]]? = nil) {
        self.status = status
        self.info = info
        self.error = error
        self.details = details
    }

}
