//
// Item.swift
//
// Generated by openapi-generator
// https://openapi-generator.tech
//

import Foundation

public struct Item: Codable {

    public var category: Category?
    public var modifierLists: [ModifierList]?
    public var variations: [Variation]?
    public var id: String?
    public var createDate: Date?
    public var updateDate: Date?
    public var squareId: String?
    public var name: String?
    public var priceInCents: Double?
    public var description: String?
    public var categoryId: String?

    public init(category: Category? = nil, modifierLists: [ModifierList]? = nil, variations: [Variation]? = nil, id: String? = nil, createDate: Date? = nil, updateDate: Date? = nil, squareId: String? = nil, name: String? = nil, priceInCents: Double? = nil, description: String? = nil, categoryId: String? = nil) {
        self.category = category
        self.modifierLists = modifierLists
        self.variations = variations
        self.id = id
        self.createDate = createDate
        self.updateDate = updateDate
        self.squareId = squareId
        self.name = name
        self.priceInCents = priceInCents
        self.description = description
        self.categoryId = categoryId
    }

}
