//
// Merchant.swift
//
// Generated by openapi-generator
// https://openapi-generator.tech
//

import Foundation

public class Merchant: Codable, Hashable {

    public var catalog: Catalog?
    public var id: String?
    public var createDate: Date?
    public var updateDate: Date?
    public var email: String?
    public var password: String
    public var firstName: String?
    public var lastName: String?
    public var phoneNumber: String?
    public var stripeId: String?
    public var stripeCheckoutSessionId: String?
    public var squareAccessTokenId: String?
    public var squareAccessToken: SquareAccessToken?

    public init(catalog: Catalog? = nil, id: String? = nil, createDate: Date? = nil, updateDate: Date? = nil, email: String? = nil, password: String, firstName: String? = nil, lastName: String? = nil, phoneNumber: String? = nil, stripeId: String? = nil, stripeCheckoutSessionId: String? = nil, squareAccessTokenId: String? = nil, squareAccessToken: SquareAccessToken? = nil) {
        self.catalog = catalog
        self.id = id
        self.createDate = createDate
        self.updateDate = updateDate
        self.email = email
        self.password = password
        self.firstName = firstName
        self.lastName = lastName
        self.phoneNumber = phoneNumber
        self.stripeId = stripeId
        self.stripeCheckoutSessionId = stripeCheckoutSessionId
        self.squareAccessTokenId = squareAccessTokenId
        self.squareAccessToken = squareAccessToken
    }

}
