//
// MoaAuthenticationOutput.swift
//
// Generated by openapi-generator
// https://openapi-generator.tech
//

import Foundation

@objc public class MoaAuthenticationOutput: NSObject, Codable {

    public enum UserType: String, Codable, CaseIterable {
        case administrator = "ADMINISTRATOR"
        case merchant = "MERCHANT"
        case customer = "CUSTOMER"
    }
    public var accessToken: String?
    public var userType: UserType?

    public init(accessToken: String? = nil, userType: UserType? = nil) {
        self.accessToken = accessToken
        self.userType = userType
    }

}
