//
// MoaAlertDto.swift
//
// Generated by openapi-generator
// https://openapi-generator.tech
//

import Foundation

@objc public class MoaAlertDto: NSObject, Codable {

    public var message: String?
    public var blocking: Bool?
    public var blockingNum: NSNumber? {
        get {
            return blocking as NSNumber?
        }
    }

    public init(message: String? = nil, blocking: Bool? = nil) {
        self.message = message
        self.blocking = blocking
    }

}
