//
// MoaAWSS3File.swift
//
// Generated by openapi-generator
// https://openapi-generator.tech
//

import Foundation

@objc public class MoaAWSS3File: NSObject, Codable {

    public var ulidKey: String?
    public var dateAndTime: Date?
    public var type: String?
    public var name: String?
    public var status: String?
    public var uploadedDate: String?
    public var percent: Double?
    public var size: Double?
    public var lastModifiedDate: String?
    public var previewUrl: String?
    public var duration: Double?
    public var width: Double?
    public var height: Double?
    public var videoWidth: Double?
    public var videoHeight: Double?
    public var thumbnailUrl: String?
    public var detailUrl: String?
    public var moaId: String?
    public var createDate: Date?
    public var updateDate: Date?
    public var deleteDate: Date?
    public var version: Double?

    public init(ulidKey: String? = nil, dateAndTime: Date? = nil, type: String? = nil, name: String? = nil, status: String? = nil, uploadedDate: String? = nil, percent: Double? = nil, size: Double? = nil, lastModifiedDate: String? = nil, previewUrl: String? = nil, duration: Double? = nil, width: Double? = nil, height: Double? = nil, videoWidth: Double? = nil, videoHeight: Double? = nil, thumbnailUrl: String? = nil, detailUrl: String? = nil, moaId: String? = nil, createDate: Date? = nil, updateDate: Date? = nil, deleteDate: Date? = nil, version: Double? = nil) {
        self.ulidKey = ulidKey
        self.dateAndTime = dateAndTime
        self.type = type
        self.name = name
        self.status = status
        self.uploadedDate = uploadedDate
        self.percent = percent
        self.size = size
        self.lastModifiedDate = lastModifiedDate
        self.previewUrl = previewUrl
        self.duration = duration
        self.width = width
        self.height = height
        self.videoWidth = videoWidth
        self.videoHeight = videoHeight
        self.thumbnailUrl = thumbnailUrl
        self.detailUrl = detailUrl
        self.moaId = moaId
        self.createDate = createDate
        self.updateDate = updateDate
        self.deleteDate = deleteDate
        self.version = version
    }

}
