//
// MoaAuthenticationInput.swift
//
// Generated by openapi-generator
// https://openapi-generator.tech
//

import Foundation

@objc public class MoaAuthenticationInput: NSObject, Codable {

    public var email: String
    public var password: String
    public var merchantId: String?

    public init(email: String, password: String, merchantId: String? = nil) {
        self.email = email
        self.password = password
        self.merchantId = merchantId
    }

}
