//
// MoaAppConfigurationDto.swift
//
// Generated by openapi-generator
// https://openapi-generator.tech
//

import Foundation

@objc public class MoaAppConfigurationDto: NSObject, Codable {

    public var alert: MoaAlertDto?
    public var requiredUpdate: Any?
    public var optionalUpdate: MoaOptionalUpdateDto?

    public init(alert: MoaAlertDto? = nil, requiredUpdate: Any? = nil, optionalUpdate: MoaOptionalUpdateDto? = nil) {
        self.alert = alert
        self.requiredUpdate = requiredUpdate
        self.optionalUpdate = optionalUpdate
    }

}
