//
// MoaCatalog.swift
//
// Generated by openapi-generator
// https://openapi-generator.tech
//

import Foundation

@objc public class MoaCatalog: NSObject, Codable {

    public var categories: [MoaCategory]?
    public var merchant: MoaMerchant?
    public var moaId: String?
    public var createDate: Date?
    public var updateDate: Date?

    public init(categories: [MoaCategory]? = nil, merchant: MoaMerchant? = nil, moaId: String? = nil, createDate: Date? = nil, updateDate: Date? = nil) {
        self.categories = categories
        self.merchant = merchant
        self.moaId = moaId
        self.createDate = createDate
        self.updateDate = updateDate
    }

}
