//
// MoaCategory.swift
//
// Generated by openapi-generator
// https://openapi-generator.tech
//

import Foundation

@objc public class MoaCategory: NSObject, Codable {

    public var catalog: MoaCatalog?
    public var items: [MoaItem]?
    public var moaId: String?
    public var createDate: Date?
    public var updateDate: Date?
    public var squareId: String?
    public var name: String?

    public init(catalog: MoaCatalog? = nil, items: [MoaItem]? = nil, moaId: String? = nil, createDate: Date? = nil, updateDate: Date? = nil, squareId: String? = nil, name: String? = nil) {
        self.catalog = catalog
        self.items = items
        self.moaId = moaId
        self.createDate = createDate
        self.updateDate = updateDate
        self.squareId = squareId
        self.name = name
    }

}
