//
// MoaConfigurationDto.swift
//
// Generated by openapi-generator
// https://openapi-generator.tech
//

import Foundation

@objc public class MoaConfigurationDto: NSObject, Codable {

    public var ios: MoaAppConfigurationDto?
    public var android: MoaAppConfigurationDto?

    public init(ios: MoaAppConfigurationDto? = nil, android: MoaAppConfigurationDto? = nil) {
        self.ios = ios
        self.android = android
    }

}
