//
// MoaCustomerUpdateInput.swift
//
// Generated by openapi-generator
// https://openapi-generator.tech
//

import Foundation

@objc public class MoaCustomerUpdateInput: NSObject, Codable {

    public var email: String?
    public var phoneNumber: String?
    public var password: String

    public init(email: String? = nil, phoneNumber: String? = nil, password: String) {
        self.email = email
        self.phoneNumber = phoneNumber
        self.password = password
    }

}
