//
// MoaCustomerCreateInput.swift
//
// Generated by openapi-generator
// https://openapi-generator.tech
//

import Foundation

@objc public class MoaCustomerCreateInput: NSObject, Codable {

    public var email: String
    public var password: String
    public var merchantMoaId: String

    public init(email: String, password: String, merchantMoaId: String) {
        self.email = email
        self.password = password
        self.merchantMoaId = merchantMoaId
    }

}
