//
// MoaError.swift
//
// Generated by openapi-generator
// https://openapi-generator.tech
//

import Foundation

@objc public class MoaError: NSObject, Codable {

    public var status: Double?

    public init(status: Double? = nil) {
        self.status = status
    }

}
