//
// MoaError.swift
//
// Generated by openapi-generator
// https://openapi-generator.tech
//

import Foundation

@objc public class MoaError: NSObject, Codable {

    public var response: Any?
    public var status: Double?

    public init(response: Any? = nil, status: Double? = nil) {
        self.response = response
        self.status = status
    }

}
