//
// MoaItem.swift
//
// Generated by openapi-generator
// https://openapi-generator.tech
//

import Foundation

@objc public class MoaItem: NSObject, Codable {

    public var category: MoaCategory?
    public var modifierLists: [MoaModifierList]?
    public var variations: [MoaVariation]?
    public var moaId: String?
    public var createDate: Date?
    public var updateDate: Date?
    public var squareId: String?
    public var name: String?
    public var priceInCents: Double?
    public var _description: String?
    public var categoryMoaId: String?

    public init(category: MoaCategory? = nil, modifierLists: [MoaModifierList]? = nil, variations: [MoaVariation]? = nil, moaId: String? = nil, createDate: Date? = nil, updateDate: Date? = nil, squareId: String? = nil, name: String? = nil, priceInCents: Double? = nil, _description: String? = nil, categoryMoaId: String? = nil) {
        self.category = category
        self.modifierLists = modifierLists
        self.variations = variations
        self.moaId = moaId
        self.createDate = createDate
        self.updateDate = updateDate
        self.squareId = squareId
        self.name = name
        self.priceInCents = priceInCents
        self._description = _description
        self.categoryMoaId = categoryMoaId
    }

    public enum CodingKeys: String, CodingKey, CaseIterable {
        case category
        case modifierLists
        case variations
        case moaId
        case createDate
        case updateDate
        case squareId
        case name
        case priceInCents
        case _description = "description"
        case categoryMoaId
    }

}
