//
// MoaModifierList.swift
//
// Generated by openapi-generator
// https://openapi-generator.tech
//

import Foundation

@objc public class MoaModifierList: NSObject, Codable {

    public enum SelectionType: String, Codable, CaseIterable {
        case single = "SINGLE"
        case multiple = "MULTIPLE"
    }
    public var item: MoaItem?
    public var modifiers: [MoaModifier]?
    public var moaId: String?
    public var createDate: Date?
    public var updateDate: Date?
    public var squareId: String?
    public var minSelectedModifiers: Double?
    public var maxSelectedModifiers: Double?
    public var enabled: Bool?
    public var enabledNum: NSNumber? {
        get {
            return enabled as NSNumber?
        }
    }
    public var name: String?
    public var selectionType: SelectionType?

    public init(item: MoaItem? = nil, modifiers: [MoaModifier]? = nil, moaId: String? = nil, createDate: Date? = nil, updateDate: Date? = nil, squareId: String? = nil, minSelectedModifiers: Double? = nil, maxSelectedModifiers: Double? = nil, enabled: Bool? = nil, name: String? = nil, selectionType: SelectionType? = nil) {
        self.item = item
        self.modifiers = modifiers
        self.moaId = moaId
        self.createDate = createDate
        self.updateDate = updateDate
        self.squareId = squareId
        self.minSelectedModifiers = minSelectedModifiers
        self.maxSelectedModifiers = maxSelectedModifiers
        self.enabled = enabled
        self.name = name
        self.selectionType = selectionType
    }

}
