//
// MoaMerchant.swift
//
// Generated by openapi-generator
// https://openapi-generator.tech
//

import Foundation

@objc public class MoaMerchant: NSObject, Codable {

    public var catalog: MoaCatalog?
    public var moaId: String?
    public var createDate: Date?
    public var updateDate: Date?
    public var email: String?
    public var firstName: String?
    public var lastName: String?
    public var phoneNumber: String?

    public init(catalog: MoaCatalog? = nil, moaId: String? = nil, createDate: Date? = nil, updateDate: Date? = nil, email: String? = nil, firstName: String? = nil, lastName: String? = nil, phoneNumber: String? = nil) {
        self.catalog = catalog
        self.moaId = moaId
        self.createDate = createDate
        self.updateDate = updateDate
        self.email = email
        self.firstName = firstName
        self.lastName = lastName
        self.phoneNumber = phoneNumber
    }

}
