//
// MoaMerchant.swift
//
// Generated by openapi-generator
// https://openapi-generator.tech
//

import Foundation

@objc public class MoaMerchant: NSObject, Codable {

    public var catalog: MoaCatalog?
    public var _id: String?
    public var createDate: Date?
    public var updateDate: Date?
    public var email: String?
    public var firstName: String?
    public var lastName: String?
    public var phoneNumber: String?

    public init(catalog: MoaCatalog? = nil, _id: String? = nil, createDate: Date? = nil, updateDate: Date? = nil, email: String? = nil, firstName: String? = nil, lastName: String? = nil, phoneNumber: String? = nil) {
        self.catalog = catalog
        self._id = _id
        self.createDate = createDate
        self.updateDate = updateDate
        self.email = email
        self.firstName = firstName
        self.lastName = lastName
        self.phoneNumber = phoneNumber
    }

    public enum CodingKeys: String, CodingKey, CaseIterable {
        case catalog
        case _id = "id"
        case createDate
        case updateDate
        case email
        case firstName
        case lastName
        case phoneNumber
    }

}
