//
// MoaOrderAddInput.swift
//
// Generated by openapi-generator
// https://openapi-generator.tech
//

import Foundation

@objc public class MoaOrderAddInput: NSObject, Codable {

    public var variationId: String
    public var quantity: Double
    public var modifiersIds: [String]?
    public var idempotencyKey: String

    public init(variationId: String, quantity: Double, modifiersIds: [String]? = nil, idempotencyKey: String) {
        self.variationId = variationId
        self.quantity = quantity
        self.modifiersIds = modifiersIds
        self.idempotencyKey = idempotencyKey
    }

}
