//
// MoaOrderPaginatedResponse.swift
//
// Generated by openapi-generator
// https://openapi-generator.tech
//

import Foundation

@objc public class MoaOrderPaginatedResponse: NSObject, Codable {

    public var entities: [MoaOrder]?
    public var count: Double?
    public var pages: Double?

    public init(entities: [MoaOrder]? = nil, count: Double? = nil, pages: Double? = nil) {
        self.entities = entities
        self.count = count
        self.pages = pages
    }

}
