//
// MoaOrderAddInput.swift
//
// Generated by openapi-generator
// https://openapi-generator.tech
//

import Foundation

@objc public class MoaOrderAddInput: NSObject, Codable {

    public var variationMoaId: String
    public var quantity: Double
    public var modifiersMoaIds: [String]?
    public var idempotencyKey: String

    public init(variationMoaId: String, quantity: Double, modifiersMoaIds: [String]? = nil, idempotencyKey: String) {
        self.variationMoaId = variationMoaId
        self.quantity = quantity
        self.modifiersMoaIds = modifiersMoaIds
        self.idempotencyKey = idempotencyKey
    }

}
