//
// MoaOptionalUpdateDto.swift
//
// Generated by openapi-generator
// https://openapi-generator.tech
//

import Foundation

@objc public class MoaOptionalUpdateDto: NSObject, Codable {

    public var optionalVersion: String?
    public var message: String?

    public init(optionalVersion: String? = nil, message: String? = nil) {
        self.optionalVersion = optionalVersion
        self.message = message
    }

}
