//
// MoaOrderCreateInput.swift
//
// Generated by openapi-generator
// https://openapi-generator.tech
//

import Foundation

@objc public class MoaOrderCreateInput: NSObject, Codable {

    public var locationMoaId: String

    public init(locationMoaId: String) {
        self.locationMoaId = locationMoaId
    }

}
