//
// MoaOrderCreateInput.swift
//
// Generated by openapi-generator
// https://openapi-generator.tech
//

import Foundation

@objc public class MoaOrderCreateInput: NSObject, Codable {

    public var locationId: String

    public init(locationId: String) {
        self.locationId = locationId
    }

}
