//
// MoaOrderCreateInput.swift
//
// Generated by openapi-generator
// https://openapi-generator.tech
//

import Foundation

@objc public class MoaOrderCreateInput: NSObject, Codable {

    public var squareLocationId: String

    public init(squareLocationId: String) {
        self.squareLocationId = squareLocationId
    }

}
