//
// MoaOrderPayInput.swift
//
// Generated by openapi-generator
// https://openapi-generator.tech
//

import Foundation

@objc public class MoaOrderPayInput: NSObject, Codable {

    public var paymentSquareId: String
    public var orderTipMoney: Double
    public var idempotencyKey: String

    public init(paymentSquareId: String, orderTipMoney: Double, idempotencyKey: String) {
        self.paymentSquareId = paymentSquareId
        self.orderTipMoney = orderTipMoney
        self.idempotencyKey = idempotencyKey
    }

}
