//
// MoaPasswordForgotInput.swift
//
// Generated by openapi-generator
// https://openapi-generator.tech
//

import Foundation

@objc public class MoaPasswordForgotInput: NSObject, Codable {

    public var email: String
    public var merchantMoaId: String?

    public init(email: String, merchantMoaId: String? = nil) {
        self.email = email
        self.merchantMoaId = merchantMoaId
    }

}
