//
// MoaSquareAccessToken.swift
//
// Generated by openapi-generator
// https://openapi-generator.tech
//

import Foundation

@objc public class MoaSquareAccessToken: NSObject, Codable {

    public var _id: String?
    public var createDate: Date?
    public var updateDate: Date?
    public var accessToken: String?
    public var tokenType: String?
    public var expiresAt: String?
    public var merchantId: String?
    public var refreshToken: String?
    public var shortLived: Bool?
    public var shortLivedNum: NSNumber? {
        get {
            return shortLived as NSNumber?
        }
    }
    public var merchant: MoaMerchant?

    public init(_id: String? = nil, createDate: Date? = nil, updateDate: Date? = nil, accessToken: String? = nil, tokenType: String? = nil, expiresAt: String? = nil, merchantId: String? = nil, refreshToken: String? = nil, shortLived: Bool? = nil, merchant: MoaMerchant? = nil) {
        self._id = _id
        self.createDate = createDate
        self.updateDate = updateDate
        self.accessToken = accessToken
        self.tokenType = tokenType
        self.expiresAt = expiresAt
        self.merchantId = merchantId
        self.refreshToken = refreshToken
        self.shortLived = shortLived
        self.merchant = merchant
    }

    public enum CodingKeys: String, CodingKey, CaseIterable {
        case _id = "id"
        case createDate
        case updateDate
        case accessToken
        case tokenType
        case expiresAt
        case merchantId
        case refreshToken
        case shortLived
        case merchant
    }

}
