//
// OrderRemoveInput.swift
//
// Generated by openapi-generator
// https://openapi-generator.tech
//

import Foundation

@objc public class MOAOrderRemoveInput: NSObject, Codable {

    public var orderVariationUid: String

    public init(orderVariationUid: String) {
        self.orderVariationUid = orderVariationUid
    }

}
