//
// OrderPaginatedResponse.swift
//
// Generated by openapi-generator
// https://openapi-generator.tech
//

import Foundation

@objc public class OrderPaginatedResponse: NSObject, Codable {

    public var entities: [Order]?
    public var count: Double?
    public var pages: Double?

    public init(entities: [Order]? = nil, count: Double? = nil, pages: Double? = nil) {
        self.entities = entities
        self.count = count
        self.pages = pages
    }

}
