//
// OrderRemoveInput.swift
//
// Generated by openapi-generator
// https://openapi-generator.tech
//

import Foundation

public class OrderRemoveInput: Codable, Hashable {

    public var orderVariationUid: String

    public init(orderVariationUid: String) {
        self.orderVariationUid = orderVariationUid
    }

}
