//
// OrderCreateInput.swift
//
// Generated by openapi-generator
// https://openapi-generator.tech
//

import Foundation

public class OrderCreateInput: Codable, Hashable {

    public var squareLocationId: String

    public init(squareLocationId: String) {
        self.squareLocationId = squareLocationId
    }

}
