//
// OrderAddInput.swift
//
// Generated by openapi-generator
// https://openapi-generator.tech
//

import Foundation

public class OrderAddInput: Codable, Hashable {

    public var squareVariationId: String
    public var quantity: Double
    public var modifiersIds: [String]?

    public init(squareVariationId: String, quantity: Double, modifiersIds: [String]? = nil) {
        self.squareVariationId = squareVariationId
        self.quantity = quantity
        self.modifiersIds = modifiersIds
    }

}
