//
// SquareBusinessHoursPeriod.swift
//
// Generated by openapi-generator
// https://openapi-generator.tech
//

import Foundation

public struct SquareBusinessHoursPeriod: Codable {

    public var dayOfWeek: String?
    public var startLocalTime: String?
    public var endLocalTime: String?

    public init(dayOfWeek: String? = nil, startLocalTime: String? = nil, endLocalTime: String? = nil) {
        self.dayOfWeek = dayOfWeek
        self.startLocalTime = startLocalTime
        self.endLocalTime = endLocalTime
    }

}
