//
// SquareCard.swift
//
// Generated by openapi-generator
// https://openapi-generator.tech
//

import Foundation

public class SquareCard: Codable, Hashable {

    public var id: String?
    public var expMonth: Double?
    public var expYear: Double?
    public var cardBrand: String?
    public var last4: String?
    public var cardholderName: String?
    public var billingAddress: SquareAddress?
    public var fingerprint: String?
    public var cardType: String?
    public var prepaidType: String?
    public var bin: String?

    public init(id: String? = nil, expMonth: Double? = nil, expYear: Double? = nil, cardBrand: String? = nil, last4: String? = nil, cardholderName: String? = nil, billingAddress: SquareAddress? = nil, fingerprint: String? = nil, cardType: String? = nil, prepaidType: String? = nil, bin: String? = nil) {
        self.id = id
        self.expMonth = expMonth
        self.expYear = expYear
        self.cardBrand = cardBrand
        self.last4 = last4
        self.cardholderName = cardholderName
        self.billingAddress = billingAddress
        self.fingerprint = fingerprint
        self.cardType = cardType
        self.prepaidType = prepaidType
        self.bin = bin
    }

}
