//
// SquareBusinessHours.swift
//
// Generated by openapi-generator
// https://openapi-generator.tech
//

import Foundation

@objc public class SquareBusinessHours: NSObject, Codable {

    public var periods: [SquareBusinessHoursPeriod]?

    public init(periods: [SquareBusinessHoursPeriod]? = nil) {
        self.periods = periods
    }

}
