//
// SquareDeleteCustomerCardInput.swift
//
// Generated by openapi-generator
// https://openapi-generator.tech
//

import Foundation

@objc public class SquareDeleteCustomerCardInput: NSObject, Codable {

    public var cardSquareId: String?

    public init(cardSquareId: String? = nil) {
        self.cardSquareId = cardSquareId
    }

}
