//
// SquareOrderRoundingAdjustment.swift
//
// Generated by openapi-generator
// https://openapi-generator.tech
//

import Foundation

@objc public class SquareOrderRoundingAdjustment: NSObject, Codable {

    public var uid: String?
    public var name: String?
    public var amountMoney: SquareMoney?

    public init(uid: String? = nil, name: String? = nil, amountMoney: SquareMoney? = nil) {
        self.uid = uid
        self.name = name
        self.amountMoney = amountMoney
    }

}
