//
// SquareLocation.swift
//
// Generated by openapi-generator
// https://openapi-generator.tech
//

import Foundation

@objc public class MOASquareLocation: NSObject, Codable {

    public var _id: String?
    public var name: String?
    public var address: SquareAddress?
    public var timezone: String?
    public var capabilities: [String]?
    public var status: String?
    public var createdAt: String?
    public var merchantId: String?
    public var country: String?
    public var languageCode: String?
    public var currency: String?
    public var phoneNumber: String?
    public var businessName: String?
    public var type: String?
    public var websiteUrl: String?
    public var businessHours: SquareBusinessHours?
    public var businessEmail: String?
    public var _description: String?
    public var twitterUsername: String?
    public var instagramUsername: String?
    public var facebookUrl: String?
    public var coordinates: SquareCoordinates?
    public var logoUrl: String?
    public var posBackgroundUrl: String?
    public var mcc: String?
    public var fullFormatLogoUrl: String?

    public init(_id: String? = nil, name: String? = nil, address: SquareAddress? = nil, timezone: String? = nil, capabilities: [String]? = nil, status: String? = nil, createdAt: String? = nil, merchantId: String? = nil, country: String? = nil, languageCode: String? = nil, currency: String? = nil, phoneNumber: String? = nil, businessName: String? = nil, type: String? = nil, websiteUrl: String? = nil, businessHours: SquareBusinessHours? = nil, businessEmail: String? = nil, _description: String? = nil, twitterUsername: String? = nil, instagramUsername: String? = nil, facebookUrl: String? = nil, coordinates: SquareCoordinates? = nil, logoUrl: String? = nil, posBackgroundUrl: String? = nil, mcc: String? = nil, fullFormatLogoUrl: String? = nil) {
        self._id = _id
        self.name = name
        self.address = address
        self.timezone = timezone
        self.capabilities = capabilities
        self.status = status
        self.createdAt = createdAt
        self.merchantId = merchantId
        self.country = country
        self.languageCode = languageCode
        self.currency = currency
        self.phoneNumber = phoneNumber
        self.businessName = businessName
        self.type = type
        self.websiteUrl = websiteUrl
        self.businessHours = businessHours
        self.businessEmail = businessEmail
        self._description = _description
        self.twitterUsername = twitterUsername
        self.instagramUsername = instagramUsername
        self.facebookUrl = facebookUrl
        self.coordinates = coordinates
        self.logoUrl = logoUrl
        self.posBackgroundUrl = posBackgroundUrl
        self.mcc = mcc
        self.fullFormatLogoUrl = fullFormatLogoUrl
    }

    public enum CodingKeys: String, CodingKey, CaseIterable {
        case _id = "id"
        case name
        case address
        case timezone
        case capabilities
        case status
        case createdAt
        case merchantId
        case country
        case languageCode
        case currency
        case phoneNumber
        case businessName
        case type
        case websiteUrl
        case businessHours
        case businessEmail
        case _description = "description"
        case twitterUsername
        case instagramUsername
        case facebookUrl
        case coordinates
        case logoUrl
        case posBackgroundUrl
        case mcc
        case fullFormatLogoUrl
    }

}
