//
// SquareRefund.swift
//
// Generated by openapi-generator
// https://openapi-generator.tech
//

import Foundation

public struct SquareRefund: Codable {

    public var id: String?
    public var locationId: String?
    public var transactionId: String?
    public var tenderId: String?
    public var createdAt: String?
    public var reason: String?
    public var amountMoney: SquareMoney?
    public var status: String?
    public var processingFeeMoney: SquareMoney?

    public init(id: String? = nil, locationId: String? = nil, transactionId: String? = nil, tenderId: String? = nil, createdAt: String? = nil, reason: String? = nil, amountMoney: SquareMoney? = nil, status: String? = nil, processingFeeMoney: SquareMoney? = nil) {
        self.id = id
        self.locationId = locationId
        self.transactionId = transactionId
        self.tenderId = tenderId
        self.createdAt = createdAt
        self.reason = reason
        self.amountMoney = amountMoney
        self.status = status
        self.processingFeeMoney = processingFeeMoney
    }

}
