//
// SquareRefund.swift
//
// Generated by openapi-generator
// https://openapi-generator.tech
//

import Foundation

@objc public class SquareRefund: NSObject, Codable {

    public var _id: String?
    public var locationId: String?
    public var transactionId: String?
    public var tenderId: String?
    public var createdAt: String?
    public var reason: String?
    public var amountMoney: SquareMoney?
    public var status: String?
    public var processingFeeMoney: SquareMoney?

    public init(_id: String? = nil, locationId: String? = nil, transactionId: String? = nil, tenderId: String? = nil, createdAt: String? = nil, reason: String? = nil, amountMoney: SquareMoney? = nil, status: String? = nil, processingFeeMoney: SquareMoney? = nil) {
        self._id = _id
        self.locationId = locationId
        self.transactionId = transactionId
        self.tenderId = tenderId
        self.createdAt = createdAt
        self.reason = reason
        self.amountMoney = amountMoney
        self.status = status
        self.processingFeeMoney = processingFeeMoney
    }

    public enum CodingKeys: String, CodingKey, CaseIterable {
        case _id = "id"
        case locationId
        case transactionId
        case tenderId
        case createdAt
        case reason
        case amountMoney
        case status
        case processingFeeMoney
    }

}
