//
// SquareCard.swift
//
// Generated by openapi-generator
// https://openapi-generator.tech
//

import Foundation

@objc public class MOASquareCard: NSObject, Codable {

    public var _id: String?
    public var expMonth: Double?
    public var expYear: Double?
    public var cardBrand: String?
    public var last4: String?
    public var cardholderName: String?
    public var billingAddress: SquareAddress?
    public var fingerprint: String?
    public var cardType: String?
    public var prepaidType: String?
    public var bin: String?

    public init(_id: String? = nil, expMonth: Double? = nil, expYear: Double? = nil, cardBrand: String? = nil, last4: String? = nil, cardholderName: String? = nil, billingAddress: SquareAddress? = nil, fingerprint: String? = nil, cardType: String? = nil, prepaidType: String? = nil, bin: String? = nil) {
        self._id = _id
        self.expMonth = expMonth
        self.expYear = expYear
        self.cardBrand = cardBrand
        self.last4 = last4
        self.cardholderName = cardholderName
        self.billingAddress = billingAddress
        self.fingerprint = fingerprint
        self.cardType = cardType
        self.prepaidType = prepaidType
        self.bin = bin
    }

    public enum CodingKeys: String, CodingKey, CaseIterable {
        case _id = "id"
        case expMonth
        case expYear
        case cardBrand
        case last4
        case cardholderName
        case billingAddress
        case fingerprint
        case cardType
        case prepaidType
        case bin
    }

}
