//
// SquareDeleteCustomerCardInput.swift
//
// Generated by openapi-generator
// https://openapi-generator.tech
//

import Foundation

@objc public class SquareDeleteCustomerCardInput: NSObject, Codable {

    public var squareCardId: String?

    public init(squareCardId: String? = nil) {
        self.squareCardId = squareCardId
    }

}
