//
// SquareOrderLineItemModifier.swift
//
// Generated by openapi-generator
// https://openapi-generator.tech
//

import Foundation

@objc public class SquareOrderLineItemModifier: NSObject, Codable {

    public var uid: String?
    public var catalogObjectId: String?
    public var name: String?
    public var basePriceMoney: SquareMoney?
    public var totalPriceMoney: SquareMoney?

    public init(uid: String? = nil, catalogObjectId: String? = nil, name: String? = nil, basePriceMoney: SquareMoney? = nil, totalPriceMoney: SquareMoney? = nil) {
        self.uid = uid
        self.catalogObjectId = catalogObjectId
        self.name = name
        self.basePriceMoney = basePriceMoney
        self.totalPriceMoney = totalPriceMoney
    }

}
