//
// SquareTender.swift
//
// Generated by openapi-generator
// https://openapi-generator.tech
//

import Foundation

@objc public class SquareTender: NSObject, Codable {

    public var _id: String?
    public var locationId: String?
    public var transactionId: String?
    public var createdAt: String?
    public var note: String?
    public var amountMoney: SquareMoney?
    public var tipMoney: SquareMoney?
    public var processingFeeMoney: SquareMoney?
    public var customerId: String?
    public var type: String?
    public var paymentId: String?

    public init(_id: String? = nil, locationId: String? = nil, transactionId: String? = nil, createdAt: String? = nil, note: String? = nil, amountMoney: SquareMoney? = nil, tipMoney: SquareMoney? = nil, processingFeeMoney: SquareMoney? = nil, customerId: String? = nil, type: String? = nil, paymentId: String? = nil) {
        self._id = _id
        self.locationId = locationId
        self.transactionId = transactionId
        self.createdAt = createdAt
        self.note = note
        self.amountMoney = amountMoney
        self.tipMoney = tipMoney
        self.processingFeeMoney = processingFeeMoney
        self.customerId = customerId
        self.type = type
        self.paymentId = paymentId
    }

    public enum CodingKeys: String, CodingKey, CaseIterable {
        case _id = "id"
        case locationId
        case transactionId
        case createdAt
        case note
        case amountMoney
        case tipMoney
        case processingFeeMoney
        case customerId
        case type
        case paymentId
    }

}
