//
// SquareAddress.swift
//
// Generated by openapi-generator
// https://openapi-generator.tech
//

import Foundation

@objc public class MOASquareAddress: NSObject, Codable {

    public var addressLine1: String?
    public var addressLine2: String?
    public var addressLine3: String?
    public var locality: String?
    public var sublocality: String?
    public var sublocality2: String?
    public var sublocality3: String?
    public var administrativeDistrictLevel1: String?
    public var administrativeDistrictLevel2: String?
    public var administrativeDistrictLevel3: String?
    public var postalCode: String?
    public var country: String?
    public var firstName: String?
    public var lastName: String?
    public var organization: String?

    public init(addressLine1: String? = nil, addressLine2: String? = nil, addressLine3: String? = nil, locality: String? = nil, sublocality: String? = nil, sublocality2: String? = nil, sublocality3: String? = nil, administrativeDistrictLevel1: String? = nil, administrativeDistrictLevel2: String? = nil, administrativeDistrictLevel3: String? = nil, postalCode: String? = nil, country: String? = nil, firstName: String? = nil, lastName: String? = nil, organization: String? = nil) {
        self.addressLine1 = addressLine1
        self.addressLine2 = addressLine2
        self.addressLine3 = addressLine3
        self.locality = locality
        self.sublocality = sublocality
        self.sublocality2 = sublocality2
        self.sublocality3 = sublocality3
        self.administrativeDistrictLevel1 = administrativeDistrictLevel1
        self.administrativeDistrictLevel2 = administrativeDistrictLevel2
        self.administrativeDistrictLevel3 = administrativeDistrictLevel3
        self.postalCode = postalCode
        self.country = country
        self.firstName = firstName
        self.lastName = lastName
        self.organization = organization
    }

}
