//
// SquareOrderFulfillment.swift
//
// Generated by openapi-generator
// https://openapi-generator.tech
//

import Foundation

@objc public class SquareOrderFulfillment: NSObject, Codable {

    public var uid: String?
    public var type: String?
    public var state: String?

    public init(uid: String? = nil, type: String? = nil, state: String? = nil) {
        self.uid = uid
        self.type = type
        self.state = state
    }

}
