//
// SquarePayment.swift
//
// Generated by openapi-generator
// https://openapi-generator.tech
//

import Foundation

public struct SquarePayment: Codable {

    public var id: String?
    public var createdAt: String?
    public var updatedAt: String?
    public var amountMoney: SquareMoney?
    public var tipMoney: SquareMoney?
    public var totalMoney: SquareMoney?
    public var appFeeMoney: SquareMoney?
    public var approvedMoney: SquareMoney?
    public var refundedMoney: SquareMoney?
    public var status: String?
    public var delayDuration: String?
    public var delayAction: String?
    public var delayedUntil: String?
    public var sourceType: String?
    public var locationId: String?
    public var orderId: String?
    public var referenceId: String?
    public var customerId: String?
    public var employeeId: String?
    public var refundIds: [String]?
    public var buyerEmailAddress: String?
    public var billingAddress: SquareAddress?
    public var shippingAddress: SquareAddress?
    public var note: String?
    public var statementDescriptionIdentifier: String?
    public var capabilities: [String]?
    public var receiptNumber: String?
    public var receiptUrl: String?
    public var versionToken: String?

    public init(id: String? = nil, createdAt: String? = nil, updatedAt: String? = nil, amountMoney: SquareMoney? = nil, tipMoney: SquareMoney? = nil, totalMoney: SquareMoney? = nil, appFeeMoney: SquareMoney? = nil, approvedMoney: SquareMoney? = nil, refundedMoney: SquareMoney? = nil, status: String? = nil, delayDuration: String? = nil, delayAction: String? = nil, delayedUntil: String? = nil, sourceType: String? = nil, locationId: String? = nil, orderId: String? = nil, referenceId: String? = nil, customerId: String? = nil, employeeId: String? = nil, refundIds: [String]? = nil, buyerEmailAddress: String? = nil, billingAddress: SquareAddress? = nil, shippingAddress: SquareAddress? = nil, note: String? = nil, statementDescriptionIdentifier: String? = nil, capabilities: [String]? = nil, receiptNumber: String? = nil, receiptUrl: String? = nil, versionToken: String? = nil) {
        self.id = id
        self.createdAt = createdAt
        self.updatedAt = updatedAt
        self.amountMoney = amountMoney
        self.tipMoney = tipMoney
        self.totalMoney = totalMoney
        self.appFeeMoney = appFeeMoney
        self.approvedMoney = approvedMoney
        self.refundedMoney = refundedMoney
        self.status = status
        self.delayDuration = delayDuration
        self.delayAction = delayAction
        self.delayedUntil = delayedUntil
        self.sourceType = sourceType
        self.locationId = locationId
        self.orderId = orderId
        self.referenceId = referenceId
        self.customerId = customerId
        self.employeeId = employeeId
        self.refundIds = refundIds
        self.buyerEmailAddress = buyerEmailAddress
        self.billingAddress = billingAddress
        self.shippingAddress = shippingAddress
        self.note = note
        self.statementDescriptionIdentifier = statementDescriptionIdentifier
        self.capabilities = capabilities
        self.receiptNumber = receiptNumber
        self.receiptUrl = receiptUrl
        self.versionToken = versionToken
    }

}
