//
// SquareAccessToken.swift
//
// Generated by openapi-generator
// https://openapi-generator.tech
//

import Foundation

public struct SquareAccessToken: Codable {

    public var id: String?
    public var createDate: Date?
    public var updateDate: Date?
    public var accessToken: String?
    public var tokenType: String?
    public var expiresAt: String?
    public var merchantId: String?
    public var refreshToken: String?
    public var shortLived: Bool?
    public var merchant: Merchant?

    public init(id: String? = nil, createDate: Date? = nil, updateDate: Date? = nil, accessToken: String? = nil, tokenType: String? = nil, expiresAt: String? = nil, merchantId: String? = nil, refreshToken: String? = nil, shortLived: Bool? = nil, merchant: Merchant? = nil) {
        self.id = id
        self.createDate = createDate
        self.updateDate = updateDate
        self.accessToken = accessToken
        self.tokenType = tokenType
        self.expiresAt = expiresAt
        self.merchantId = merchantId
        self.refreshToken = refreshToken
        self.shortLived = shortLived
        self.merchant = merchant
    }

}
