//
// SquareMoney.swift
//
// Generated by openapi-generator
// https://openapi-generator.tech
//

import Foundation

public struct SquareMoney: Codable {

    public var amount: Any?
    public var currency: String?

    public init(amount: Any? = nil, currency: String? = nil) {
        self.amount = amount
        self.currency = currency
    }

}
