//
// SquareOrderLineItemTax.swift
//
// Generated by openapi-generator
// https://openapi-generator.tech
//

import Foundation

@objc public class SquareOrderLineItemTax: NSObject, Codable {

    public var uid: String?
    public var catalogObjectId: String?
    public var name: String?
    public var type: String?
    public var percentage: String?
    public var appliedMoney: SquareMoney?
    public var scope: String?
    public var autoApplied: Bool?
    public var autoAppliedNum: NSNumber? {
        get {
            return autoApplied as NSNumber?
        }
    }

    public init(uid: String? = nil, catalogObjectId: String? = nil, name: String? = nil, type: String? = nil, percentage: String? = nil, appliedMoney: SquareMoney? = nil, scope: String? = nil, autoApplied: Bool? = nil) {
        self.uid = uid
        self.catalogObjectId = catalogObjectId
        self.name = name
        self.type = type
        self.percentage = percentage
        self.appliedMoney = appliedMoney
        self.scope = scope
        self.autoApplied = autoApplied
    }

}
