//
// Variation.swift
//
// Generated by openapi-generator
// https://openapi-generator.tech
//

import Foundation

public struct Variation: Codable {

    public var item: Item?
    public var id: String?
    public var createDate: Date?
    public var updateDate: Date?
    public var squareId: String?
    public var name: String?
    public var priceInCents: Double?

    public init(item: Item? = nil, id: String? = nil, createDate: Date? = nil, updateDate: Date? = nil, squareId: String? = nil, name: String? = nil, priceInCents: Double? = nil) {
        self.item = item
        self.id = id
        self.createDate = createDate
        self.updateDate = updateDate
        self.squareId = squareId
        self.name = name
        self.priceInCents = priceInCents
    }

}
