//
// AuthenticationAPI.swift
//
// Generated by openapi-generator
// https://openapi-generator.tech
//

import Foundation

@objc open class AuthenticationAPI : NSObject {
    /**

     - parameter moaAuthenticationInput: (body)  
     - parameter apiResponseQueue: The queue on which api response is dispatched.
     - parameter completion: completion handler to receive the data and the error objects
     */
    open class func postAuthentication(moaAuthenticationInput: MoaAuthenticationInput, apiResponseQueue: DispatchQueue = MyOrderAppSwiftAPI.apiResponseQueue, completion: @escaping ((_ data: MoaAuthenticationOutput?, _ error: Error?) -> Void)) {
        postAuthenticationWithRequestBuilder(moaAuthenticationInput: moaAuthenticationInput).execute(apiResponseQueue) { result -> Void in
            switch result {
            case let .success(response):
                completion(response.body, nil)
            case let .failure(error):
                completion(nil, error)
            }
        }
    }

    /**
     - POST /v1/authentication
     - parameter moaAuthenticationInput: (body)  
     - returns: RequestBuilder<MoaAuthenticationOutput> 
     */
    open class func postAuthenticationWithRequestBuilder(moaAuthenticationInput: MoaAuthenticationInput) -> RequestBuilder<MoaAuthenticationOutput> {
        let path = "/v1/authentication"
        let URLString = MyOrderAppSwiftAPI.basePath + path
        let parameters = JSONEncodingHelper.encodingParameters(forEncodableObject: moaAuthenticationInput)

        let url = URLComponents(string: URLString)

        let nillableHeaders: [String: Any?] = [
            :
        ]

        let headerParameters = APIHelper.rejectNilHeaders(nillableHeaders)

        let requestBuilder: RequestBuilder<MoaAuthenticationOutput>.Type = MyOrderAppSwiftAPI.requestBuilderFactory.getBuilder()

        return requestBuilder.init(method: "POST", URLString: (url?.string ?? URLString), parameters: parameters, headers: headerParameters)
    }

}
