//
// MerchantsAPI.swift
//
// Generated by openapi-generator
// https://openapi-generator.tech
//

import Foundation

@objc open class MerchantsAPI : NSObject {
    /**

     - parameter apiResponseQueue: The queue on which api response is dispatched.
     - parameter completion: completion handler to receive the result
     */
    open class func getSquareLocationForCurrentCustomersMerchant(apiResponseQueue: DispatchQueue = MyOrderAppSwiftAPI.apiResponseQueue, completion: @escaping ((_ result: Swift.Result<[SquareLocation], Error>) -> Void)) {
        getSquareLocationForCurrentCustomersMerchantWithRequestBuilder().execute(apiResponseQueue) { result -> Void in
            switch result {
            case let .success(response):
                completion(.success(response.body!))
            case let .failure(error):
                completion(.failure(error))
            }
        }
    }

    /**
     - GET /v1/merchants/current/square/locations
     - BASIC:
       - type: http
       - name: bearer
     - returns: RequestBuilder<[SquareLocation]> 
     */
    open class func getSquareLocationForCurrentCustomersMerchantWithRequestBuilder() -> RequestBuilder<[SquareLocation]> {
        let path = "/v1/merchants/current/square/locations"
        let URLString = MyOrderAppSwiftAPI.basePath + path
        let parameters: [String: Any]? = nil

        let url = URLComponents(string: URLString)

        let nillableHeaders: [String: Any?] = [
            :
        ]

        let headerParameters = APIHelper.rejectNilHeaders(nillableHeaders)

        let requestBuilder: RequestBuilder<[SquareLocation]>.Type = MyOrderAppSwiftAPI.requestBuilderFactory.getBuilder()

        return requestBuilder.init(method: "GET", URLString: (url?.string ?? URLString), parameters: parameters, headers: headerParameters)
    }

}
